# NumPy 


O NumPy é uma Biblioteca de Álgebra Linear para Python, o motivo pelo qual é tão importante para a Ciência de Dados com Python é que quase todas as bibliotecas do Ecossistema PyData confiam no NumPy como um de seus principais blocos de construção.

O Numpy também é rápido, pois possui ligações para as bibliotecas C. Para obter mais informações sobre por que você gostaria de usar matrizes em vez de listas, confira em [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Instruções de instalação

** É altamente recomendável instalar o Python usando a distribuição Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de álgebra linear) sejam sincronizadas com o uso de uma instalação conda. Se você possui o Anaconda, instale o NumPy acessando o terminal ou prompt de comando e digitando: **
    
    conda install numpy
    
**Se você não possui o Anaconda e não pode instalá-lo, consulte a documentação oficial do Numpy em várias instruções de instalação.(http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [2]:
import numpy as np

O Numpy possui muitas funções e recursos internos. Não abordaremos todos eles, mas focaremos alguns dos aspectos mais importantes do Numpy: vetores, matrizes, matrizes e geração de números. Vamos começar discutindo matrizes.

# Numpy Arrays

As matrizes NumPy são a principal maneira de usarmos o Numpy ao longo do curso. Matrizes numpy vêm basicamente em dois sabores: vetores e matrizes. Os vetores são estritamente matrizes 1-d e matrizes são 2-d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes NumPy.

## Criando matrizes NumPy

### De uma lista Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos internos

Existem várias maneiras internas de gerar matrizes


### arange

Retorne valores espaçados uniformemente dentro de um determinado intervalo.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])


### zeros e uns

Gere matrizes de zeros ou uns

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

### linspace

Retornar números espaçados uniformemente em um intervalo especificado.

In [3]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

## eye


Cria uma matriz de identidade

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

O Numpy também tem várias maneiras de criar matrizes de números aleatórios:

### rand
Crie uma matriz da forma especificada e preencha-a com
amostras aleatórias de uma distribuição uniforme
sobre `` [0, 1) ``.

In [22]:
np.random.rand(2)

array([0.84096249, 0.87238726])

In [23]:
np.random.rand(5,5)

array([[0.85728245, 0.45837258, 0.69803911, 0.07347334, 0.74948883],
       [0.48168167, 0.82437747, 0.19724844, 0.68298619, 0.71332744],
       [0.47405239, 0.46258135, 0.76643493, 0.75098367, 0.79005228],
       [0.30435025, 0.25610093, 0.60337122, 0.94489081, 0.45928982],
       [0.28410655, 0.81528141, 0.33221429, 0.18434226, 0.60276017]])

### randn


Retorne uma amostra (ou amostras) da distribuição "normal normal". Ao contrário do rand, que é uniforme:

In [20]:
np.random.randn(2)

array([-0.745631  ,  0.25623815])

In [ ]:
ii=np.random.randn(500,25000)
ii.max()

### randint
Retorne números inteiros aleatórios de `baixo` (inclusive) para` alto` (exclusivo).

In [5]:
np.random.randint(1,100)

84

In [6]:
np.random.randint(1,100,10)

array([66, 63, 67, 59, 67, 58, 40, 60,  5, 50])


## Atributos e métodos de matriz

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
ranarr

array([49, 24, 32, 47, 29, 29, 42, 32, 29, 26])

## Reshape
Retorna uma matriz que contém os mesmos dados com uma nova forma.

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos. Ou para encontrar seus locais de índice usando argmin ou argmax

In [15]:
ranarr

array([49, 24, 32, 47, 29, 29, 42, 32, 29, 26])

In [16]:
ranarr.max()

49

In [17]:
ranarr.argmax()

0

In [18]:
ranarr.min()

24

In [19]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [7]:
# Vector
arr.shape

NameError: name 'arr' is not defined

In [8]:
# Notice the two sets of brackets
arr.reshape(1,25)

NameError: name 'arr' is not defined

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype


Você também pode pegar o tipo de dados do objeto na matriz:

In [ ]:
arr.dtype


# Bom trabalho!